### ISSUE TITLE
HTML and CSS payment feed admin settings not very nice

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay-gravityforms#23]
I have added a description to the trial period settings in https://github.com/pronamic/wp-pronamic-pay-gravityforms/commit/2731300f7f6a125eb02448fb063fcd0ca05d7f0e:

- https://github.com/pronamic/wp-pronamic-pay-gravityforms/issues/13#issuecomment-1380973181

The display is not very nice:

<img width="926" alt="Scherm­afbeelding 2023-01-12 om 21 43 56" src="https://user-images.githubusercontent.com/869674/212177476-e95c4cc1-09e7-46ca-b959-0d7facd0cabf.png">

There is a negative margin:

```css
#gf-pay-feed-editor .pronamic-gf-subscription-tab fieldset > div {
    margin-bottom: -1em;
    margin-left: 2em;
}
```

https://github.com/pronamic/wp-pronamic-pay-gravityforms/blob/2731300f7f6a125eb02448fb063fcd0ca05d7f0e/scss/admin.scss#L47-L53
